# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c4a26173510f542edad46e43aab5587"
name = "Remobu Advisor"
application_url = "https://example.com"
handle = "remobu-advisor"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
