name = "Remobu App"
client_id = "9b4f8be68cc8f78b7a2691949fb40de4"
application_url = "https://remobu-app-production.up.railway.app"
embedded = true

[auth]
redirect_urls = [
  "https://remobu-app-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2026-07"

[pos]
embedded = false
