api_version = "2025-01"

[[extensions]]
name = "mpesa-payment"
handle = "mpesa-payment"
type = "payment_customization"

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.payment-customization.run"
