api_version = "2025-01"

[[extensions]]
name = "mpesa-payment"
handle = "mpesa-payment"
uid = "2ca298cd-b039-e5be-2dfc-b2541cba5988494ce1e4"
type = "payment_customization"

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.payment-customization.run"
